### ISSUE TITLE
:sparkles: 用户列表

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [A-Minos/nonebot-plugin-tetris-stats#346]
新页面 `v2/tetrio/user/list`

数据传递参考: [https://github.com/A-Minos/tetris-stats-templates/blob/main/src/v2/components/tests/tetrio_user_list.vue](https://github.com/A-Minos/tetris-stats-templates/blob/main/src/v2/components/tests/tetrio_user_list.vue)

# API
查 `CN` 前五十: `/users/lists/league?country=CN&limit=50`
> `limit` 默认值为 `50`

**Comment by shoucandanghehe** [comment]
用什么命令触发呢（
